ALTER TABLE worker_applications 
ADD COLUMN IF NOT EXISTS consent_to_contact BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS consent_timestamp TIMESTAMP,
ADD COLUMN IF NOT EXISTS consent_ip TEXT;
